version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}desafio
    build:
      context: ./desafio
      dockerfile: Dockerfile-api
    environment:
       - ASPNETCORE_URLS=http://+:80
    ports:
       - "80:80"
    container_name: desafio-api